spring.application.name=backend
server.port=8080

# ===== Base de datos H2 en memoria =====
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA / Hibernate =====
# ddl-auto=update: crea/actualiza las tablas automáticamente desde las entidades
spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL generado en consola (muy Util para aprender)
spring.jpa.show-sql=true

# ===== Consola web de H2 (http://localhost:8080/h2-console) =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.web.error.include-message=always
